sudo: false
language: ruby
services:
  - postgresql
before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.2.5
  - 2.3.1
  - 2.3.3
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
script: "bundle exec rake spec"
